name: audio_school
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  retrofit: ^4.0.1
  retrofit_generator: ^6.0.0+1
  formz: ^0.4.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path_provider: ^2.0.13
  animated_splash_screen: ^1.3.0
  #audio
  rxdart: ^0.27.7
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  just_audio: ^0.9.18
  audio_session: ^0.1.6
  #api
  chopper: ^6.1.1
  dio: ^5.1.1


dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/logo-dark.png
    - assets/images/test.png

